#+title: flymake-overlays.el: Toggleable overlays for Flymake diagnostics
#+author: Paul Nelson

* Overview
The =flymake-overlays= package enhances Flymake diagnostics by providing toggleable overlays below the affected lines.  It introduces a minor mode, =flymake-overlays-mode=, that can be activated to display these overlays.

When active, this mode creates overlays for each Flymake diagnostic.  These overlays are initially hidden, but can be toggled on and off individually, allowing you to view detailed diagnostic information without cluttering your buffer.

* Configuration
Download this repository, install using =M-x package-install-file= (or package-vc-install, straight, elpaca, ...), and add something like the following to your [[https://www.emacswiki.org/emacs/InitFile][init file]]:

#+begin_src elisp
(use-package flymake-overlays
  :after flymake
  :bind (:map flymake-mode-map
              ("C-c t" . flymake-overlays-smart-toggle))
  :hook (flymake-mode . flymake-overlays-mode))
#+end_src

Customize the bindings as you like.  The =:hook= line ensures that =flymake-overlays-mode= is activated whenever =flymake-mode= is.

The =flymake-overlays-smart-toggle= function toggles the overlay at point if there is one, otherwise it toggles all overlays in the buffer.

* Usage
Once configured, =flymake-overlays-mode= will automatically create overlays for Flymake diagnostics.  To interact with these overlays:

- Use =M-x flymake-overlays-toggle-at-point= (or your custom keybinding) to toggle the visibility of the overlay at point.
- The overlays update automatically when Flymake reports new diagnostics.

* Customization
You can customize the appearance and behavior of the overlays:

- The face =flymake-overlays-face= controls the appearance of the overlay text.
- The variable =flymake-overlays-fontify-text-fn= allows you to customize how the diagnostic text is fontified. By default, it uses the current major mode's fontification.

To customize these, use =M-x customize-group RET flymake-overlays RET=.
